---
- name: create a partition, then use LVM and create a volume then filesystem + mount
  hosts: all
  vars_files:
    - vars/storage.yml
  tasks:
    - name: create a partition
      parted:
        device: /dev/sdb
        state: present
        number: "{{ item.number }}"
        part_start: "{{ item.start }}"
        part_end: "{{ item.end }}"
      loop: "{{ partitions }}"

    - name: create volume group
      lvg:
        vg: "{{ item.name }}"
        pvs: "{{ item.devices }}"
      loop: "{{ vgs }}"

    - name: create logical volume
      lvol:
        vg: "{{ item.vgroup }}"
        lv: "{{ item.name }}"
        size: "{{ item.size }}"
      loop: "{{ lvs }}"

    - name: create filesystem
      filesystem:
        dev: "/dev/{{ item.vgroup }}/{{ item.name }}"
        fstype: xfs
      loop: "{{ lvs }}"

    - name: mount the LV
      mount:
        path: /mnt/ansible/test
        src: "/dev/{{ item.vgroup }}/{{ item.name }}"
        fstype: xfs
        state: mounted
      loop: "{{ lvs }}"

