---
- name: unmount and delete part
  hosts: all
  tasks:
    - name: umount /dev/
      mount:
        path: /mnt/testmounti
        state: absent

    - name: delete the LV
      lvol:
        lv: logical-volume
        vg: volume-group
        state: absent
        force: yes

    - name: delete the VG
      lvg:
        vg: volume-group
        state: absent
        force: yes

    - name: delete partition
      parted:
        device: /dev/sdb
        state: absent
        number: 1
...
